token:
  expiration_time: 8640000
  secret: user_token_dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "{cipher}76432305ef5aa837c0eb53a174a7c43beb382bfc0f795c82d24e6b84ecaccfe7"
gateway:
  ip: 172.18.0.5
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
